language: node_js

node_js: ["0.12", "4", "6"]

addons:
    apt:
        packages:
            - libqrencode3
            - libqrencode-dev
            - libpng12-0
            - libpng12-dev

sudo: false
dist: trusty
