language: node_js

env:
    - CXX=g++-4.8

node_js: ["0.12", "4", "6"]

addons:
    apt:
        packages:
            - g++-4.8
            - libqrencode3
            - libqrencode-dev
            - libpng12-0
            - libpng12-dev

before_install:
    - $CXX --version

dist: trusty
